modLoader = "javafml"
loaderVersion = "[46,)"
license = "${mod_license}"
issueTrackerURL = "${mod_issue_tracker}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = '''${mod_description}'''
    logoFile = "icon.png"

[["dependencies.${mod_id}"]]
    modId = "forge"
    type = "required"
    ordering = "NONE"
    side = "CLIENT"

[["dependencies.${mod_id}"]]
    modId = "minecraft"
    type = "required"
    side = "CLIENT"